name: .NET

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x
      - name: Restore
        run: dotnet tool restore
      - name: Paket install
        run: dotnet paket install
      - name: Test
        run: dotnet fake build -t RunTests
